# Generated by Django 2.0.4 on 2018-07-12 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='图表名称')),
                ('chart_option', models.TextField(verbose_name='图表选项')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='EChartProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(max_length=255, verbose_name='图表类型')),
                ('title', models.CharField(max_length=255, verbose_name='显示名称')),
                ('axis', models.BooleanField(default=False, verbose_name='是否坐标轴')),
                ('chart_field', models.CharField(max_length=255, verbose_name='图表字段')),
                ('field', models.CharField(max_length=255, verbose_name='字段名称')),
                ('order', models.IntegerField(verbose_name='排序号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='EChartPropertyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_value', models.CharField(max_length=255, verbose_name='选项值')),
                ('value', models.TextField(verbose_name='属性值')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dazzlingShow.EChart', verbose_name='图形')),
                ('proper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dazzlingShow.EChartProperty', verbose_name='属性')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='echartproperty',
            unique_together={('chart_type', 'chart_field')},
        ),
    ]
