# Generated by Django 2.0.4 on 2018-07-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dazzlingShow', '0004_auto_20180712_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='echartproperty',
            name='options',
            field=models.TextField(blank=True, default='', verbose_name='下拉框选项'),
        ),
    ]
