# Generated by Django 2.0.4 on 2018-07-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dazzlingShow', '0005_echartproperty_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='echartproperty',
            name='default',
            field=models.TextField(default='', verbose_name='默认值'),
        ),
    ]
